version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev #look into current directory and get dockerfile of that name
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev #look into current directory and get dockerfile of that name
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # override default command 